name: Swift

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: pods
      run: pod install
    - name: build
      run: xcodebuild -workspace Pock.xcworkspace -scheme Pock -configuration Debug
